import Link from "next/link";
import Head from "next/head";
import React, { ReactNode } from "react";

type Props = {
    title: string | undefined,
    children: ReactNode
}

const PageLayout = ({
    children,     
    title = "Storefront",    
}: Props) => {
    return (
        <>
    <Head>
         <title>{title}</title>
            <meta charSet="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
            <meta name="description" content="Generated by create next app" />
    </Head>
    <main>
        <Link href="/Home">Home</Link>
        <Link href="/postsprops">Posts with Static Props</Link>
        <Link href="/postsstatic">Posts with Static Content</Link>
        <Link href="/postsapi">Posts with Api</Link>
        {children}            
    </main>
    <footer>    
    <Link href="/Home">Home</Link>
        <Link href="/postsprops">Posts with Static Props</Link>
        <Link href="/postsstatic">Posts with Static Content</Link>
        <Link href="/postsapi">Posts with Api</Link>
    </footer>
    </>
    );
}

export default PageLayout;